const board = {
  "cell-start": { name: "Деньги", type: "money", next: ["cell-1"] },
  "cell-1": { name: "Расходы", type: "expenses", next: ["cell-2"] },
  "cell-2": { name: "Шанс", type: "chance", next: ["cell-3"] },
  "cell-3": { name: "Новости", type: "news", next: ["cell-4"] },
  "cell-4": { name: "Мечта компьютер", type: "dreamComputer", price: 600, next: ["cell-5"] },
  "cell-5": { name: "Расходы", type: "expenses", next: ["cell-6"] },
  "cell-6": { name: "Детский бизнес", type: "kidsBusiness", next: ["cell-7"] },
  "cell-7": { name: "Шанс", type: "chance", next: ["cell-8"] },
  "cell-8": { name: "Новости", type: "news", next: ["cell-fork1"] },
  "cell-fork1": { name: "Развилка", type: "fork", next: ["cell-9", "cell-13"] },
  "cell-9": { name: "Деньги", type: "money", next: ["cell-10"] },
  "cell-10": { name: "Детский бизнес", type: "kidsBusiness", next: ["cell-11"] },
  "cell-11": { name: "Расходы", type: "expenses", next: ["cell-12"] },
  "cell-12": { name: "Шанс", type: "chance", next: ["cell-44"] },
  "cell-13": { name: "Директор", type: "director", next: ["cell-14"] },
  "cell-14": { name: "Расходы", type: "expenses", next: ["cell-15"] },
  "cell-15": { name: "Новости", type: "news", next: ["cell-16"] },
  "cell-16": { name: "Шанс", type: "chance", next: ["cell-17"] },
  "cell-17": { name: "Расходы", type: "expenses", next: ["cell-18"] },
  "cell-18": { name: "Мечта велосипед", type: "dreamBicycle", price: 600, next: ["cell-fork"] },
  "cell-fork": { name: "Развилка", type: "fork", next: ["cell-19", "cell-25"] },
  "cell-19": { name: "Шанс", type: "chance", next: ["cell-20"] },
  "cell-20": { name: "Новости", type: "news", next: ["cell-21"] },
  "cell-21": { name: "Деньги", type: "money", next: ["cell-22"] },
  "cell-22": { name: "Расходы", type: "expenses", next: ["cell-23"] },
  "cell-23": { name: "Детский бизнес", type: "kidsBusiness", next: ["cell-24"] },
  "cell-24": { name: "Драка", type: "fight1", next: ["cell-38"] },
  "cell-25": { name: "Хулиганы", type: "gang", next: ["cell-26"] },
  "cell-26": { name: "Расходы", type: "expenses", next: ["cell-27"] },
  "cell-27": { name: "Новости", type: "news", next: ["cell-28"] },
  "cell-28": { name: "Большие проблемы", type: "bigProblem", next: ["cell-29"] },
  "cell-29": { name: "Мечта смартфон", type: "dreamSmartphone", price: 500, next: ["cell-30"] },
  "cell-30": { name: "Расходы", type: "expenses", next: ["cell-31"] },
  "cell-31": { name: "Драка", type: "fight2", next: ["cell-32"] },
  "cell-32": { name: "Новости", type: "news", next: ["cell-33"] },
  "cell-33": { name: "Расходы", type: "expenses", next: ["cell-34"] },
  "cell-34": { name: "Мечта компьютер", type: "dreamComputer", price: 600, next: ["cell-35"] },
  "cell-35": { name: "Хулиганы", type: "gang", next: ["cell-36"] },
  "cell-36": { name: "Расходы", type: "expenses", next: ["cell-37"] },
  "cell-37": { name: "Новости", type: "news", next: ["cell-38"] },
  "cell-38": { name: "Шанс", type: "chance", next: ["cell-39"] },
  "cell-39": { name: "Деньги", type: "money", next: ["cell-40"] },
  "cell-40": { name: "Расходы", type: "expenses", next: ["cell-41"] },
  "cell-41": { name: "Благотворительность", type: "charity", next: ["cell-42"] },
  "cell-42": { name: "Детский бизнес", type: "kidsBusiness", next: ["cell-43"] },
  "cell-43": { name: "Шанс", type: "chance", next: ["cell-44"] },
  "cell-44": { name: "Новости", type: "news", next: ["cell-45"] },
  "cell-45": { name: "Мечта электросамокат", type: "dreamScooter", price: 600, next: ["cell-46"] },
  "cell-46": { name: "Деньги", type: "money", next: ["cell-47"] },
  "cell-47": { name: "Расходы", type: "expenses", next: ["cell-48"] },
  "cell-48": { name: "Шанс", type: "chance", next: ["cell-49"] },
  "cell-49": { name: "Новости", type: "news", next: ["cell-50"] },
  "cell-50": { name: "Мечта поездка в Дисней ленд", type: "dreamDisneyland", price: 1000, next: ["cell-51"] },
  "cell-51": { name: "Деньги", type: "money", next: ["cell-52"] },
  "cell-52": { name: "Расходы", type: "expenses", next: ["cell-53"] },
  "cell-53": { name: "Детский бизнес", type: "kidsBusiness", next: ["cell-54"] },
  "cell-54": { name: "Новости", type: "news", next: ["cell-55"] },
  "cell-55": { name: "Шанс", type: "chance", next: ["cell-start"] }
};

module.exports = board;